### ISSUE TITLE
Random File Corruption

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#172] opened 2017-08-31 18:03 UTC
If I open a project in MJML app I am getting random corruption of my MJML files when I close the app. I get 0KB files as such:

![image](https://user-images.githubusercontent.com/4194561/29937930-b7e2d67a-8e4c-11e7-897a-6dbc441e97c6.png)

Not sure what's going on or how to resolve. Thoughts, @meriadec ?

**Comment by dshastry** [comment] 2017-08-31 18:03
Other files are OK. Only index.mjml is affected

![image](https://user-images.githubusercontent.com/4194561/29937970-d6da6566-8e4c-11e7-82c9-3b09fb1ed310.png)

**Comment by meriadec** [comment] 2017-08-31 20:13
Hum... that's problematic :(
So how to reproduce? Do you create a project from the project creation modal, or do you open an existing project? Can you upload a zip of a project that make the app reproduce the problem when opening?

**Comment by dshastry** [comment] 2017-09-01 15:55
So to be honest, its very hard to reproduce because its extremely random. No specific event/behavior triggers it but this is the third time it's happened in about 4 months. Thankfully since its in a google drive folder I am able to recover from previous version.

Here are possible steps for replication:
1 - Create new/edit existing template inside MJML app (file exists in google drive/dropbox folder)
2 - Close MJML app with keyboard shortcut (CMD+Q)
3 - Reopen and check previously edited file may be empty. Other mjml files in folder not impacted

It has happened to me when I create, but I see it more when opening an existing folder on disk. Zip of my project folder attached, but I deleted and recovered the corrupted file so not sure how much help it is. Nothing really missing much though. When the file is corrupted all contents are deleted and its just a 0 byte file with the same file name. If I open in Brackets the file is completely empty (no spaces,or any characters)


[MJML Error.zip](https://github.com/mjmlio/mjml-app/files/1270797/MJML.Error.zip)

**Comment by Mistra** [comment] 2017-09-20 14:59
Hello, I had similar issues with another program when I had many writings all at the same time in a **syncing folder**. I believe the problem is actually dropbox / gdrive autosync itself.

This is my thought:
As far as I can see MJML app saves the files basically every time you edit something, each time you save the underlying program **syncs**. Most of the times it's smooth, but sometimes I think it could be we have a problem that reminds a lot dataracing on the hard drive.

Have you tried working on a folder **not** in sync? You can always paste your work when you are done (or use git to save at the end). Try it that way to see if the problem goes away.

**Comment by meriadec** [comment] 2017-09-20 15:11
I agree that having disc syncing programs running on the same files can lead to problems, as MJML App is constantly saving to disk everytime you change a single character.

Following https://github.com/mjmlio/mjml-app/issues/158, I think that when we will have a real "Save" button, with "unsaved" state for a template, that would drastically the number of file system calls, and I'm sure that will reduce a lot that kind of problems.

**Comment by dshastry** [comment] 2017-09-20 15:39
Thanks @Mistra. Agreed. I do believe it's Google drive because I've had other issues with it in some other programs as well. I'll try working on a folder not in sync and copy over and report back. Save button would be fantastic @meriadec!

Thanks for the help, guys

**Comment by meriadec** [comment] 2018-03-07 10:52
closing in favor of #219

**Closed by meriadec** 2018-03-07 10:52 UTC
