### ISSUE TITLE
Windows Release v1.6

### ISSUE THREAD

**Issue by modulexcite** [mjmlio/mjml-app#66] opened 2016-12-16 03:51 UTC
Thank for a wonderful project.
I don't see an option to download v1.6 for windows platform either in the releases section or on the website, is it being discontinued for windows platform?

**Comment by meriadec** [comment] 2016-12-16 09:05
Hi @modulexcite,

Don't worry, we will sure not discontinue Windows platform support :)
Windows builds come usually a bit later on mjml-app releases, because we have... to boot on Windows to build it 😄 .

@janus-reith , if you still are OK, it will be awesome if u could provide the Windows binary for 1.6.0. I can build Linux release this week-end.

**Comment by modulexcite** [comment] 2016-12-16 14:19
That's great to hear. You guys rock! :metal:

**Comment by janus-reith** [comment] 2016-12-16 15:00
Yep, I'm on it

**Comment by meriadec** [comment] 2016-12-18 12:42
Hmm.. yep, I've reproduced your problem while doing a "fresh install" (git clone + npm install from scratch). Some packages apparently messed things up (I didn't dig too much). 

Fortunately, you can use `yarn` to install deps instead of `npm install`, so you will have exact dependencies that works (just tested in my Linux, and it's ok).

I'm uploading linux release right now.

Long life to yarn.

**Comment by janus-reith** [comment] 2016-12-20 09:27
yarn also didn't work OOTB, had to remove the optional appdmg from package.json, although optional it prevented yarn from installing any package.

It did indeed solve the issue, the windows release is uploaded now.

Closing this, maybe we should open a separate issue about the npm dependency problem,
will have to dig further into this when I have the time.

**Closed by janus-reith** 2016-12-20 09:27 UTC
Labels: question

**Comment by meriadec** [comment] 2016-12-20 09:34
Thanks Janus!

Yes, I had too to remove appdmg from deps while installing with yarn on Linux. Maybe we should remove appdmg from our deps? What dyou think @ngarnier @GuillaumeBadi ?

@modulexcite Windows release is here!

**Comment by ngarnier** [comment] 2016-12-20 09:53
Awesome, thanks @janus-reith! 

@meriadec, I guess we could remove it from the deps and install it manually. We could also add the issue in the readme and notice that `npm install --no-optional` should be used on Windows and Linux?

**Comment by janus-reith** [comment] 2016-12-20 10:04
For me this just affected yarn, npm just skipped this package on win and linux, also without the `--no-optional` parameter.
Looking at the yarn git, it seems like they have to deal with some issues regarding optional deps.

**Comment by modulexcite** [comment] 2016-12-20 11:37
Thanks for the windows release, however I no longer get an update notification from the app(v1.5) about a new release. I initially got a brief notification about a new release and that's what prompted me to post this issue here. I'm not sure it's related but thought I should point out.
