### ISSUE TITLE
Template crashes on load in application

### ISSUE THREAD

**Issue by woodbine** [mjmlio/mjml-app#265] opened 2018-10-05 16:07 UTC
TypeError: n.unshift is not a function
    at payload (file:///Applications/MJML.app/Contents/Resources/app.asar/webpack:/src/reducers/settings.js:36:29)
    at updateInDeepMap (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1278:26)
    at Map.update (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:1270:14)
    at lastEmails (file:///Applications/MJML.app/Contents/Resources/app.asar/webpack:/src/reducers/settings.js:31:52)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/redux-actions/lib/handleAction.js:67:64
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/reduce-reducers/dist/index.js:14:14
    at Array.reduce (<anonymous>)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/reduce-reducers/dist/index.js:13:21
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/redux-actions/lib/handleActions.js:56:12
    at combination (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/redux/lib/combineReducers.js:133:29)
    at dispatch (/Applications/MJML.app/Contents/Resources/app.asar/node_modules/redux/lib/createStore.js:178:22)
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/react-router-redux/lib/middleware.js:22:18
    at /Applications/MJML.app/Contents/Resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at snippetContent (file:///Applications/MJML.app/Contents/Resources/app.asar/webpack:/src/reducers/snippets.js:8:45)

**Comment by ngarnier** [comment] 2018-10-05 16:21
Your issue is made of a javascript error, and solely that. You have to understand that it makes it very difficult, for us maintainers, to help you (and I'll be honest, frustrating as well). What are we supposed to do? How did it happen? Can we reproduce it to track it down and try to solve it? How? 

Please have a read at [this](https://github.com/mjmlio/mjml/blob/master/ISSUE_TEMPLATE.md) or [this](https://github.com/mjmlio/mjml/blob/master/ISSUE_TEMPLATE.md) to see how to create an issue that we can solve.

**Comment by woodbine** [comment] 2018-10-06 08:45
Sorry, I really have very little experience in reporting issues so bear with me. I just started the app, selected the template and then I saw a screen pop up explaining that I should report the error, so I copied the text and followed the link to report the issue. I naively assumed that the data you would need on the error was contained within the text I then pasted.

I was using the mjml application on a mac (High Sierra 10.13.5), I loaded the following template https://mjml.io/try-it-live/templates/recast. The load was taking a while (I was on a slightly flaky connection) so I went to another window, when I came back to the mjml app, the error was showing.

I've not been able to recreate the error. (New projects with the same template load fine).

I'm sorry if this isn't helpful, I was simply following the prompts that your software gave me. Perhaps you could add the links about how to report an issue to these prompts so that uneducated users like me know what to do.

**Comment by ngarnier** [comment] 2018-10-08 08:19
Thank you for the additional information, this is more helpful :). I've tried reproducing the issue but like you I wasn't able to (trying to change the folder to a git repo, switching the connection off when fetching templates...). 

As we can't reproduce the issue I will close it but feel free to reopen it if you find a way, and thanks for reporting initially (understood your confusion about the prompt, we'll see how we can improve it too).

**Closed by ngarnier** 2018-10-08 08:19 UTC
