### ISSUE TITLE
Code editor do not take empty space if I disable preview

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml-app#37] opened 2016-05-10 09:03 UTC
Check this gif. 
![screencast 77s1o](https://cloud.githubusercontent.com/assets/77309/15141088/0eef6f00-16bc-11e6-9d8f-6ca1832238aa.gif)

**Comment by GuillaumeBadi** [comment] 2016-05-10 09:05
Hey ! Can you provide some details about your environment ?

**Comment by jitendravyas** [comment] 2016-05-10 09:09
I'm on OSX Yosemite 10.10.5.

**Comment by GuillaumeBadi** [comment] 2016-05-10 09:21
I cannot reproduce the error on my side, weird. Any chance you get it to load in dev mode (Build from source) ?
<img width="851" alt="screen shot 2016-05-08 at 00 08 46" src="http://g.recordit.co/AQuU04rVEQ.gif">

**Comment by meriadec** [comment] 2016-05-10 11:11
Strange. The only difference I see between the two gifs is that @jitendravyas is on "wrap text mode" and you re not @GuillaumeBadi. Can you try with wrap text enabled?

**Comment by meriadec** [comment] 2016-05-10 11:32
Ok I just tested with wrap text enabled in editor, and I reproduced the bug. Should be easy to fix, I'm on it.

**Comment by meriadec** [comment] 2016-05-10 13:29
Will be fixed in next release.

![wrap_low mov](https://cloud.githubusercontent.com/assets/315259/15148066/eacda18e-16c3-11e6-9db1-03d7919b1f40.gif)

**Closed by meriadec** 2016-05-10 13:29 UTC
Labels: bug
